<?php
return [
  'adrianaperez' => [
    'slug' => 'adrianaperez',
    'name' => 'ADRIANA PEREZ',
    'email' => 'info@aplslegal.com',
    'view' => 'adrianaperez',
    'photo' => '/img/members/adrianaperez.png',
    'title' => 'Adriana Perez',
    'claim' => 'Su despacho legal & fiscal de confianza',
    'desc' => 'Somos un pequeño despacho de abogados internacional multidisciplinar, haciendo nuestras las preocupaciones de nuestros clientes.',
    'tel' => '968 33 41 78',
    'web' => 'https://aplslegal.com/',
    'web_txt' => 'www.aplslegal.com',
    'mail' => 'info@aplslegal.com',
  ],

  'asinter' => [
    'slug' => 'asinter',
    'name' => 'ASINTER',
    'email' => 'filoasinter@gmail.com',
    'view' => 'asinter',
    'photo' => '/img/members/asinter.png',
    'title' => 'Asinter',
    'claim' => 'Asesoría Internacional',
    'desc' => 'Asesoría jurídica internacional de confianza con más de 25 años de experiencia. Civil, laboral, mercantil y administrativo, además de servicios extrajudiciales.',
    'tel' => '966 71 88 30',
    'web' => 'https://asinterlawyers.com/',
    'web_txt' => 'www.asinterlawyers.com',
    'mail' => 'filoasinter@gmail.com',
  ],

  'blauabogados' => [
    'slug' => 'blauabogados',
    'name' => 'BLAU ABOGADOS',
    'email' => 'info@ejemplo.com',
    'view' => 'blauabogados',
    'photo' => '/img/members/blauabogados.png',
    'title' => 'Blau Abogados',
    'claim' => '',
    'desc' => 'Especializados en Derecho Inmobiliario, Urbanismo e Internacional. Asesoría a particulares y empresas, especialmente a clientes extranjeros, en compraventas, inversiones, herencias y fiscalidad.',
    'tel' => '965 718 795',
    'web' => 'https://blauabogados.com/',
    'web_txt' => 'www.blauabogados.com',
    'mail' => 'info@blauabogados.com',
  ],

  'blgabogados' => [
    'slug' => 'blgabogados',
    'name' => 'BLG ABOGADOS',
    'email' => '',
    'view' => 'blgabogados',
    'photo' => '/img/members/blgabogados.png',
    'title' => 'Blg Abogados',
    'claim' => '',
    'desc' => 'Multidisciplinar especializado en Inmobiliario, Sucesiones, Extranjería, Fiscal y Civil. Asesoramiento integral a clientes nacionales e internacionales.',
    'tel' => '966 704 977',
    'web' => 'http://www.blgabogados.es/',
    'web_txt' => 'www.blgabogados.es',
    'mail' => '',
  ],

  'easylegals' => [
    'slug' => 'easylegals',
    'name' => 'EASY LEGALS',
    'email' => 'info@easylegals.com',
    'view' => 'easylegals',
    'photo' => '/img/members/easylegals.png',
    'title' => 'Easy Legals',
    'claim' => '',
    'desc' => 'Facilitamos la compra de propiedades en España para clientes internacionales. Conveyancing, herencias, impuestos, NIE y asesoría clara en varios idiomas.',
    'tel' => '966 765 024',
    'web' => 'https://easylegals.com/',
    'web_txt' => 'www.easylegals.com',
    'mail' => 'info@easylegals.com',
  ],

  'fernandezmonfort' => [
    'slug' => 'fernandezmonfort',
    'name' => 'Fernández & Monfort',
    'email' => 'info@ejemplo.com',
    'view' => 'fernandez&monfort',
    'photo' => '/img/members/fernandez&monfort.png',
    'title' => 'Fernandez Y Monfort',
    'claim' => '',
    'desc' => 'Despacho en Orihuela especializado en Inmobiliario, Herencias, Contratación y Extranjería. Enfoque en clientes extranjeros que compran en España.',
    'tel' => '966 730 264',
    'web' => 'https://fernandezabogado.es/',
    'web_txt' => 'www.fernandezabogado.es',
    'mail' => 'info@fernandezabogado.es',
  ],

  'imontlegal' => [
    'slug' => 'imontlegal',
    'name' => 'IMONT LEGAL & TAXES',
    'email' => 'info@imontlegal.com',
    'view' => 'imontlegal',
    'photo' => '/img/members/imontlegal.png',
    'title' => 'Imont Legal',
    'claim' => '',
    'desc' => 'Oficinas en varias ciudades. Inmobiliario, Familia, Sucesiones, Nacionalidad y Extranjería. Atención integral y multilingüe para clientes internacionales.',
    'tel' => '968 195 045',
    'web' => 'https://imontlegal.com/',
    'web_txt' => 'www.imontlegal.com',
    'mail' => 'info@imontlegal.com',
  ],

  'interlexunion' => [
    'slug' => 'interlexunion',
    'name' => 'INTER LEX UNION',
    'email' => 'solicitors@lexunion.es',
    'view' => 'interlexunion',
    'photo' => '/img/members/interlexunion.png',
    'title' => 'Interlex Union',
    'claim' => '',
    'desc' => 'Más de treinta años de experiencia profesional en el derecho inmobiliario garantizan sus inversiones.',
    'tel' => '966 706 986',
    'web' => 'https://interlexunion.com/',
    'web_txt' => 'www.interlexunion.com',
    'mail' => 'solicitors@lexunion.es',
  ],

  'mamsolicitors' => [
    'slug' => 'mamsolicitors',
    'name' => 'MAM Solicitors',
    'email' => '',
    'view' => 'mamsolicitors',
    'photo' => '/img/members/mamsolicitors.png',
    'title' => 'MAM Solicitors',
    'claim' => 'YOUR TRUSTED LAW FIRM IN SPAIN',
    'desc' => 'Costa Blanca y Costa Cálida. Inmobiliario, Sucesiones, Extranjería y Fiscalidad. +30 años asesorando a clientes internacionales.',
    'tel' => '968 334 439',
    'web' => 'https://mamsolicitors.com/',
    'web_txt' => 'www.mamsolicitors.com',
    'mail' => '',
  ],

  'manchonabogados' => [
    'slug' => 'manchonabogados',
    'name' => 'Manchón Abogados',
    'email' => 'manchon@manchonabogados.com',
    'view' => 'manchonabogados',
    'photo' => '/img/members/manchonabogados.png',
    'title' => 'Manchon Abogados',
    'claim' => '',
    'desc' => 'Sede en Elche. Inmobiliario, Civil, Sucesiones y Extranjería. Asesoramiento a clientes nacionales e internacionales.',
    'tel' => '625 11 00 50',
    'web' => 'https://manchonabogados.com/',
    'web_txt' => 'www.manchonabogados.com',
    'mail' => 'manchon@manchonabogados.com',
  ],

  'marenostrum' => [
    'slug' => 'marenostrum',
    'name' => 'Eugenio Pedreño Balibrea',
    'email' => 'eugeniopb@mnostrumlaw.com',
    'view' => 'marenostrum',
    'photo' => '/img/members/marenostrum.png',
    'title' => 'Mare Nostrum',
    'claim' => 'Mare Nostrum Law & Tax, S.L.P.',
    'desc' => 'Asesoría legal para clientes internacionales: inmobiliario, sucesiones, fiscalidad y servicio personalizado en su idioma.',
    'tel' => '968 13 73 74',
    'web' => 'https://www.mnostrumlaw.com',
    'web_txt' => 'www.mnostrumlaw.com',
    'mail' => 'eugeniopb@mnostrumlaw.com',
  ],

  'nmn-abogados' => [
    'slug' => 'nmn-abogados',
    'name' => 'NMN Abogados',
    'email' => 'info@nmnabogados.com',
    'view' => 'nmn',
    'photo' => '/img/members/nmn.png',
    'title' => 'NMN Abogados',
    'claim' => '',
    'desc' => 'Multidisciplinar en Alicante: Inmobiliario, Extranjería, Sucesiones, Fiscal, Civil y Penal. Atención cercana a clientes nacionales e internacionales.',
    'tel' => '643 122 515',
    'web' => 'https://www.nmnabogados.com/',
    'web_txt' => 'www.nmnabogados.com',
    'mail' => 'info@nmnabogados.com',
  ],

  'sgm' => [
    'slug' => 'sgm',
    'name' => 'SGM ABOGADOS',
    'email' => 'info@sgm.com',
    'view' => 'sgm',
    'photo' => '/img/members/sgm.png',
    'title' => 'Sgm Abogados',
    'claim' => '',
    'desc' => 'Despacho experto en Derecho Inmobiliario, Sucesiones, Extranjería y Fiscalidad para clientes internacionales: compraventas, testamentos, NIE, residencia y representación fiscal.',
    'tel' => '965 72 48 71',
    'web' => 'https://sgmlegalspain.com/',
    'web_txt' => 'www.sgmlegalspain.com',
    'mail' => 'info@sgmlegalspain.com',
  ],

  'sol4' => [
    'slug' => 'sol4',
    'name' => 'Sol4',
    'email' => 'info@sol-4gestion.com',
    'view' => 'sol4',
    'photo' => '/img/members/sol4.png',
    'title' => 'Sol4',
    'claim' => 'Investment & Consulting',
    'desc' => 'Asesoría integral para residentes y no residentes: gestión inmobiliaria, fiscal, legal y administrativa. Compraventas, herencias, NIE e impuestos.',
    'tel' => '966 715 181',
    'web' => 'https://sol-4gestion.com/',
    'web_txt' => 'www.sol-4gestion.com',
    'mail' => 'info@sol-4gestion.com',
  ],

  'sunlawyers' => [
    'slug' => 'sunlawyers',
    'name' => 'SUN LAWYERS',
    'email' => 'admin@sun-lawyers.com',
    'view' => 'sunlawyers',
    'photo' => '/img/members/sunlawyers.png',
    'title' => 'Sun Lawyers',
    'claim' => '',
    'desc' => 'Más de 30 años en Costa Blanca. Inmobiliario, Sucesiones, Fiscalidad y Extranjería para clientes internacionales.',
    'tel' => '965 321 193',
    'web' => 'https://sun-lawyers.com/',
    'web_txt' => 'www.sun-lawyers.com',
    'mail' => 'admin@sun-lawyers.com',
  ],

  'visonalawyers' => [
    'slug' => 'visonalawyers',
    'name' => 'VISONA LAWYERS',
    'email' => 'info@visonalawyers.com',
    'view' => 'visonalawyers',
    'photo' => '/img/members/visonalawyers.png',
    'title' => 'Visona Lawyers',
    'claim' => 'Making Law Make Sense',
    'desc' => 'Despacho multidisciplinar en Costa Blanca con amplia experiencia en asesorar a clientes españoles y extranjeros.',
    'tel' => '966 843 701',
    'web' => 'https://visonalawyers.com/',
    'web_txt' => 'www.visonalawyers.com',
    'mail' => 'info@visonalawyers.com',
  ],

  'fabiankesseli' => [
    'slug' => 'fabiankesseli',
    'name' => 'FABIAN KESSELI',
    'email' => 'fabian.kesseli@icaorihuela.com',
    'view' => 'fabiankesseli',
    'photo' => '/img/members/fabiankesseli.jpg',
    'title' => 'Fabián Kesseli',
    'claim' => 'SU ABOGADO EN SU CASA',
    'desc' => 'Asesoría legal personalizada en España para residentes y no residentes, con especial foco en la costa de Murcia y Alicante.',
    'tel' => '696 15 69 73',
    'web' => 'https://www.ihranwaltinsuedostspanien.com',
    'web_txt' => 'www.ihranwaltinsuedostspanien.com',
    'mail' => 'fabian.kesseli@icaorihuela.com',
  ],

  'cuencaasociados' => [
    'slug' => 'cuencaasociados',
    'name' => 'CUENCA ABOGADOS ASOCIADOS',
    'email' => 'info@cuencaasociados.com',
    'view' => 'cuencaasociados',
    'photo' => '/img/members/cuencaasociados.png',
    'title' => 'Cuenca Abogados',
    'claim' => 'Expertos legales en Murcia y Alicante',
    'desc' => 'Despacho de abogados y economistas con más de 20 años de experiencia, con oficinas en Murcia y Pilar de la Horadada (Alicante).',
    'tel' => '+34 968 90 96 68',
    'web' => 'https://cuencaasociados.com/',
    'web_txt' => 'www.cuencaasociados.com',
    'mail' => 'info@cuencaasociados.com',
  ],

  'mflsolicitors' => [
    'slug' => 'mflsolicitors',
    'name' => 'MLF SOLICITORS',
    'email' => 'scfabogado@gmail.com',
    'view' => 'mlfsolicitors',
    'photo' => '/img/members/mlfsolicitors.png',
    'title' => 'MLF Solicitors',
    'claim' => 'Nuestros clientes son el corazón de nuestra organización',
    'desc' => 'Despacho jurídico con un equipo de abogados y asistentes legales comprometidos, enfocados en ofrecer un servicio cercano y orientado al cliente.',
    'tel' => '+34 966 723 620',
    'web' => 'https://mlfsolicitors.com',
    'web_txt' => 'mlfsolicitors.com',
    'mail' => 'scfabogado@gmail.com',
  ],

];
